### ISSUE TITLE
Allow developers to alter MapField height

### ISSUE THREAD

**Issue by phptek** [smindel/silverstripe-gis#5] opened 2019-01-21 21:20 UTC
It would be good if developers could manipulate the default height of the auto-scaffolded `MapField` using a familliar API e.g. `->setHeight()` or even mimicing `HTMLTextEditor`'s `->setRows()`.

At the moment, the default height of the map is a little narrow. Of course I appreciate it auto-expands on hover, which would still be useful. In addition, maybe add a `->setDisableHoverBehaviour()` or similar.

**Comment by smindel** [comment] 2019-01-22 09:16
Nice idea, the hover behaviour can be annoying tbh. Added to my list. Cheers

**Comment by smindel** [comment] 2019-03-05 22:24
Closing this one because it's not a bug. Happy to consider PRs though.

**Closed by smindel** 2019-03-05 22:24 UTC
Labels: enhancement
